packages:
  - .

overrides:
  vite: "$vite"
  '@vitejs/plugin-vue': 6.0.4
  '@vitejs/plugin-vue-jsx': ^5.1.5
  esbuild: ^0.25.0
  brace-expansion: ^2.0.3
  tar: ^7.5.11
  node-forge: ^1.4.0
  glob: ^10.5.0
  js-yaml: ^4.1.1
  flatted: ^3.4.2
  h3: ^1.15.6
  defu: ^6.1.5
  devalue: ^5.8.1
  serialize-javascript: ^7.0.3
  minimatch@3: ^3.1.4
  minimatch@10: ^10.2.5

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

strictPeerDependencies: false
